//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.MaterialInStocks = new HashSet<MaterialInStock>();
        }
    
        public int CurrencyID { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<decimal> CurrentRate { get; set; }
        public Nullable<decimal> LastRate { get; set; }
    
        public virtual ICollection<MaterialInStock> MaterialInStocks { get; set; }
    }
}
