//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialHistory
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string UserName { get; set; }
        public string TransactionName { get; set; }
        public Nullable<decimal> OldStock { get; set; }
        public Nullable<decimal> NewStock { get; set; }
        public string Note { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public Nullable<int> StoreID { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Store Store { get; set; }
    }
}
