//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public string MaterialType { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string Notes { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Order Order { get; set; }
        public virtual Store Store { get; set; }
    }
}
