//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailsData
    {
        public string CustomerName { get; set; }
        public string UnitName { get; set; }
        public string MaterialNo { get; set; }
        public string MaterialName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Width { get; set; }
        public int ID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string UserName { get; set; }
        public string Notes { get; set; }
        public string StoreName { get; set; }
        public string ItemNotes { get; set; }
    }
}
