//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservedMaterial
    {
        public int ID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> ReservedDate { get; set; }
        public string Note { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> Paid { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<int> MaterialInStock { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual MaterialInStock MaterialInStock1 { get; set; }
    }
}
