//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.DeadMaterials = new HashSet<DeadMaterial>();
            this.CuttingListsMaterials = new HashSet<CuttingListsMaterial>();
            this.MaterialInStocks = new HashSet<MaterialInStock>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Transfers = new HashSet<Transfer>();
            this.Transfers1 = new HashSet<Transfer>();
            this.MaterialHistories = new HashSet<MaterialHistory>();
            this.ContainerDatas = new HashSet<ContainerData>();
        }
    
        public int ID { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public string StoreLocation { get; set; }
        public string StoreName { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<long> PhoneNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<DeadMaterial> DeadMaterials { get; set; }
        public virtual ICollection<CuttingListsMaterial> CuttingListsMaterials { get; set; }
        public virtual ICollection<MaterialInStock> MaterialInStocks { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Transfer> Transfers { get; set; }
        public virtual ICollection<Transfer> Transfers1 { get; set; }
        public virtual ICollection<MaterialHistory> MaterialHistories { get; set; }
        public virtual ICollection<ContainerData> ContainerDatas { get; set; }
    }
}
