//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Materials = new HashSet<Material>();
            this.MaterialInStocks = new HashSet<MaterialInStock>();
        }
    
        public int SupplierID { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public string ContactPerson { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Rate { get; set; }
    
        public virtual ICollection<Material> Materials { get; set; }
        public virtual ICollection<MaterialInStock> MaterialInStocks { get; set; }
    }
}
