//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public Transfer()
        {
            this.TransferDetails = new HashSet<TransferDetail>();
        }
    
        public int ID { get; set; }
        public int SerialNo { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string UserName { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> FromStore { get; set; }
        public Nullable<int> ToStore { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual Store Store1 { get; set; }
        public virtual ICollection<TransferDetail> TransferDetails { get; set; }
        public virtual Transfer Transfers1 { get; set; }
        public virtual Transfer Transfer1 { get; set; }
    }
}
