//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.DeadMaterials = new HashSet<DeadMaterial>();
            this.Materials = new HashSet<Material>();
            this.CuttingListsMaterials = new HashSet<CuttingListsMaterial>();
            this.MaterialInStocks = new HashSet<MaterialInStock>();
        }
    
        public int ID { get; set; }
        public string UnitName { get; set; }
        public string UnitSymbol { get; set; }
    
        public virtual ICollection<DeadMaterial> DeadMaterials { get; set; }
        public virtual ICollection<Material> Materials { get; set; }
        public virtual ICollection<CuttingListsMaterial> CuttingListsMaterials { get; set; }
        public virtual ICollection<MaterialInStock> MaterialInStocks { get; set; }
    }
}
